apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intermediate-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moh-amer/helm-app.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: default